server:
  port: 8082
  tomcat:
    threads:
      max: 1
      min-spare: 1
    max-connections: 1
    accept-count: 1
    connection-timeout: 20000


spring:
  application:
    name: likelion-backend
  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: likelion
    password: likelion
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

custom:
#  env: dev
  env: ${CUSTOM_ENV:dev}

