name: Deploy Spring Boot App

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build:
    name: Build JAR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build project with Gradle
        run: ./gradlew clean build -x test

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: likelion-backend-jar
          path: build/libs/likelion-backend-0.0.1-SNAPSHOT.jar

  transfer:
    name: Transfer JAR to Server
    runs-on: ubuntu-latest
    needs: build  # build가 끝나야 실행됨

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: likelion-backend-jar

      - name: Setup SSH and Transfer JAR file
        run: |
          mkdir -p /home/runner/.ssh
          echo -e "${{ secrets.PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> /home/runner/.ssh/known_hosts
          scp -i /home/runner/.ssh/id_rsa likelion-backend-0.0.1-SNAPSHOT.jar \
              ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/inspire12/deploy/

  deploy:
    name: Restart & Run Application
    runs-on: ubuntu-latest
    needs: transfer  # transfer가 끝나야 실행됨

    steps:
      - name: Execute deploy script on server
        run: |
          ssh -i /home/runner/.ssh/id_rsa ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            chmod +x /home/inspire12/deploy/deploy.sh
            /home/inspire12/deploy/deploy.sh
          EOF