name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-jar
          path: build/libs/*.jar

  send:
    name: Send JAR to Server
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-jar
          path: .

      - name: SCP JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "*.jar"
          target: "/home/${{ secrets.SERVER_USER }}/deploy"


  deploy:
    name: Deploy Application
    needs: send
    runs-on: ubuntu-latest

    steps:
      - name: Execute deploy.sh on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            chmod +x /home/${{ secrets.SERVER_USER }}/deploy/deploy.sh
            sh /home/${{ secrets.SERVER_USER }}/deploy/deploy.sh